### ISSUE TITLE
Wrong signup page

### ISSUE THREAD

**Issue by wvdvegt** [gorco/gf#33]
When i go to the signup page at

http://145.20.132.23:3000/signup

I see a form with username/email/password and a create my account button, but no choice of the type of account. As (mention in the previous issue) i cannot see my roles I have no clue what role i have.

Even as the first logged in user (my guess the admin) I cannot see what role I'm supposed to full-fill.

**Comment by RotaruDan** [comment]
Hello,

After the latest release (1.0.1: https://github.com/e-ucm/rage-analytics-frontend/releases/tag/1.0.1) 
the frontend is accessible at `<a2_url:a2_port>/api/proxy/afront/login`.

In your example, I'm guessing it would be: `http://145.20.132.23:3000/api/proxy/afront/login` and `http://145.20.132.23:3000/api/proxy/afront/signup`

Keeping the analytics-frontend behind the A2 module allows us to expose only one port (A2_PORT) to the outside world. This way it's easier to proxy everything behing Nginx and use HTTPS.

Best regards,
 Dan.

**Comment by wvdvegt** [comment]
Thanks that did the trick. We dit not put nginx in front yet in order to see wether everything was working as before.
