### ISSUE TITLE
How to delete users

### ISSUE THREAD

**Issue by wvdvegt** [gorco/gf#34]
Hi

Due to the previous issues i have some accounts I whish to delete (student1 is an admin it seems). Is there any user management available (or is it foreseen in the near future)?

**Comment by gorco** [comment]
We don't have a view/button to delete users, for now.

You can delete a user using the API call `DELETE /users/:userId` with the admin credentials (root/root by default)
http://e-ucm.github.io/a2/#api-Users-DeleteUser

**Comment by wvdvegt** [comment]
That worked (except for the credentials are not used themselves in the rest request but the auth token you obtain with them when logging in).

**Comment by gorco** [comment]
Yeah, I wanted to say (with the admin credentials) that a user can't delete another user.
